version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "06:00"
    timezone: "Europe/Lisbon"
- package-ecosystem: bun
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "05:30"
    timezone: "Europe/Lisbon"